"""Slice prompt_source.txt to exact token counts and regenerate infer/prompts.py.

Run only when the lengths or the source text change:

    uv run python scripts/build_prompts.py

A slice of N token ids does not necessarily re-encode to N tokens — decoding
ids and re-tokenizing the resulting string can merge or split at the boundary.
So each length is solved for: nudge the slice until the emitted string
tokenizes to exactly the target, then assert it.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from transformers import AutoTokenizer  # noqa: E402

from infer.core import MODEL_NAME  # noqa: E402

SOURCE = ROOT / "scripts" / "prompt_source.txt"
TARGET = ROOT / "infer" / "prompts.py"

LENGTHS = {"p16": 16, "p64": 64, "p256": 256, "p1024": 1024, "p4096": 4096}


def exact_slice(ids: list[int], tok, n: int) -> str:
    """Return a string that tokenizes to exactly n tokens."""
    k = n
    for _ in range(64):
        text = tok.decode(ids[:k])
        actual = len(tok(text).input_ids)
        if actual == n:
            return text
        k += n - actual
        if k < 1 or k > len(ids):
            break
    raise SystemExit(f"could not land on exactly {n} tokens")


def as_literal(text: str, indent: str = "        ") -> str:
    """Wrapped implicit-concatenation literal, so the file stays readable."""
    chunks, line = [], ""
    for word in text.split(" "):
        candidate = f"{line} {word}" if line else word
        if len(candidate) > 88 and line:
            chunks.append(line + " ")
            line = word
        else:
            line = candidate
    if line:
        chunks.append(line)
    body = "\n".join(f"{indent}{chunk!r}" for chunk in chunks)
    return f"(\n{body}\n{indent[:-4]})"


def main() -> None:
    tok = AutoTokenizer.from_pretrained(MODEL_NAME, local_files_only=True)
    ids = tok(SOURCE.read_text()).input_ids

    longest = max(LENGTHS.values())
    if len(ids) < longest + 32:
        raise SystemExit(
            f"source text is {len(ids)} tokens, need >= {longest + 32} "
            f"for the {longest}-token prompt"
        )

    prompts = {label: exact_slice(ids, tok, n) for label, n in LENGTHS.items()}

    for label, text in prompts.items():
        assert len(tok(text).input_ids) == LENGTHS[label], label

    entries = "\n".join(
        f"    {label!r}: {as_literal(prompts[label])}," for label in LENGTHS
    )
    counts = "\n".join(f"    {label!r}: {n}," for label, n in LENGTHS.items())

    TARGET.write_text(
        '"""Benchmark prompts, sliced to exact token counts.\n\n'
        "Generated by scripts/build_prompts.py from scripts/prompt_source.txt.\n"
        "Edit those, not this file.\n"
        '"""\n\n'
        f"PROMPTS = {{\n{entries}\n}}\n\n"
        f"PROMPT_TOKENS = {{\n{counts}\n}}\n"
    )
    print(f"wrote {TARGET} ({len(ids)} tokens available in source)")
    for label, n in LENGTHS.items():
        print(f"  {label:<7} {n:>5} tokens")


if __name__ == "__main__":
    main()
